### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by ale-saglia** [n4n0GH/hello#81]
Hello, I really love your project (even if is stopped) and I really like to port to my pref distro, Void Linux. I've also seen some other user requesting information for compiling for this distro (#64 #70).

I'm working on a template to compile automatically with xbps-src and I would like to add it to the main distro repo but I don't know which license this project used (and if it's possible to redistribute compiled package).

**Comment by n4n0GH** [comment]
Since these are different projects merged into a bigger "collection", there should be license files scattered throughout the directories (like https://github.com/n4n0GH/hello/blob/master/window-decoration/COPYING) so I guess you'd have to check out each single sub project and check out the licensing on each of them. Sorry, no other way to do this since the work is based off of existing sources.
